name: Run tests

on:
  [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Get changed files
        id : changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            images/svg/**.svg
        env:
          CHANGED-FILES: $${{ steps.changed-files.outputs.all_changed_files }}
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm test
